INSERT INTO `candidates`(`name`, `description`) VALUES ('Sean Conway', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Benjamin Ambard', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('David Smith', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jamie Christie', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kathryn Jane Savery', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jane Hiatt', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Catherine Smith', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('James Miles', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tim Bohm', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Slade Minson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tim Hollo', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Alicia Payne', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Andrew Leigh', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Nathan Kuster', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Timothy Peter Elton', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Lucia Grant', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Natasa Sojic', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Guy Jakeman', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('David Coleman', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Elouise Ivy Cocker', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Marika Momircevski', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Natalie Hanna', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Steve Khouw', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Malcolm Phillip Heffernan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Zhi Soon', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Linda Burney', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Dimitri Honos', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Taylor Vandijk', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('John Goody', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Phillip Pollard', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('John August', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tony Adams', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Dougal Cameron', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Simon Kennedy', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rhys Ian Collyer', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Victor Waterson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jerome Laxale', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kyinzom Dhongdue', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Nicholas Samios', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tania Salitra', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rhiannon Bosma', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Julian Leeser', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Brendan Michael Clarke', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Benson Koschinski', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('David James Louie', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Roger Woodward', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Christopher Martinic', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Benjamin Caswell', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Adam Stepanoff', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Oz Guney', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Linda Eisler', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jason Clare', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Elvis Sinosic', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Nicolette Boele', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('David Gordon Brigden', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Martin Cousins', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Janine Kitson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rob Fletcher', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Paul Fletcher', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Michael Lowe', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kate Hook', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Stacey Whittaker', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kay Nankervis', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sarah Elliott', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Andrew Gee', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Adam John Jannis', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Amit Batish', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Zvetanka Raskov', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ammar Khan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ben Roughley', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sujan Selventhiran', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jugandeep Singh', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ed Husic', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Gaye Cameron', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Catherine Dyson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Scott Morrison', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jacqueline Guinane', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Simon Earle', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Faye Aspiotis', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Keith Mcmullen', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Pat Conaghan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Caz Heise', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Simon Chaseling', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Joshua Stephen Fairhall', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Timothy Nott', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Marcus Uren', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ben Britton', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Alison Byrnes', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Alexis Garnaut-Miller', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Dylan Green', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Michael Glover', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Thomas Grogan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Geoff Barnes', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Dean James Mackin', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Michael Feneley', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Cath Connor', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Martin Stevenson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Eliot Metherell', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Emma Mcbride', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('James Holgate', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Maxwell Holmes', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kristy Mcbain', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Greg Butler', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Darren Scott Garnon', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jerry Nockles', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Vivian Harris', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Toni Mclennan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Andrew Thaler', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Boyd Shannon', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Eli Davern', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sussan Ley', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Amanda Duncan-Strelec', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Paul Britton', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ian Christopher Roworth', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Richard Francis', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Julie Ramos', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Darren Michael Cameron', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kristina Keneally', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Lela Lepa Panich', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Peter Ronald Runge', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Dai Le', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Courtney Nguyen', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tony Margos', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Avery Howard', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Andrew Constance', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Nina Digiglio', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Carmel Mccallum', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jordan Lindsay Maloney', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jerremy Eid', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Adrian Fadini', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Fiona Phillips', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('David Bruce Smith', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Anthony Albanese', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ben Zhang', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('James Haggerty', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sarina Kilham', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Paul Henselin', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Michael Armando Dello-Iacovo', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rachael Jacobs', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Mark Andrew Rex', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Michelle Rowland', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Adam Kachwalla', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Riccardo Umberto Guerrino Bosi', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Love Preet Singh Nanda', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rick Turner', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Pradeep Pathi', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Damien Atkins', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jenny Ware', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Pete Thompson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Georgia Steele', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Craig Kelly', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Narelle Seymour', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Linda Seymour', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Riley Campbell', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Greg Baines', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Garry Trevor Dollin', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rebecca Thompson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sheneli Meneripitiyage Dona', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ross Edward Seller', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Karen Stewart', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Angus Taylor', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Joaquim Eduardo De Lima', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Penny Ackery', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Janet Murray', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Dan Repacholi', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Victoria Davies', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Stuart Bonds', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Cathy Townsend', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Geoff Passfield', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('James Thomson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Dale Mcnamara', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Scott Fulvio Laruffa', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Stuart Davis', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Darrin Marr', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Anthony Tawaf', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Grace Tan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Matt Thistlethwaite', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Trevor Ross', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Pieter Morssink', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Max Jago', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Joseph O`Connor', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Melissa Mcintosh', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Gareth Mcclure', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rebekah Ray', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Joanne Pearce', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Joel Putland', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('David Gillespie', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Alex Simpson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Steve Attkins', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Mark Hornshaw', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Josephine Cashman', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Karl Attenborough', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jayden Rivera', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Binod Paudel', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Mike Freelander', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rosa Antonia Sicari', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Scott Korman', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Adam Zahra', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Barry Steele', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Darren Dickson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sophie Scamps', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Paula Goodman', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jason Falinski', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Christopher Thomas Ball', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ethan Hrnjak', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tony Pettitt', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Susan Templeman', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Nicole Evans', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('James Jackson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Greg Keightley', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tony Hickey', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Michelle Palmer', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sarah Richards', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Chris Bowen', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Marie Saliba', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Scott Ford', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Vivek Singha', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Astrid O`Neill', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Cameron Shamsabad', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Clinton Mead', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Linda Daniel', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Matt Cox', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Immanuel Selvaraj', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Donald Mckenzie', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Alex Hawke', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Pavlo Samios', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Cindy Anne Duncan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Natasha Ledger', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Barnaby Joyce', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Matt Sharpham', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Richard Thomas', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Carol Sparks', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Laura Hughes', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Garth Pywell', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Charlotte Mccabe', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Amanda Cook', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sharon Claydon', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('William Hussey', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Katrina Wark', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Mark James Watson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Emily Brollo', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('William Bourke', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Robert Nalbandian', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Heather Armstrong', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Victor Kline', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Lesley Kinney', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Dajen Tinkler', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Trent Zimmerman', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kylea Jane Tink', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Michael Walls', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Catherine Renshaw', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Thomas Searles', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Donna Pike', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kashmir Miller', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Heather Mary Smith', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Patrick Deegan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Brett Rodney Duroux', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ian Williamson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kevin Hogan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Hanabeth Luke', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Serge Killingbeck', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Derek Hardman', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Peter Rothwell', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Deborah Swinbourn', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Mark Coulton', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Petrus Van Der Steen', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Stuart Howe', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jack Ayoub', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Trish Frail', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Benjamin Fox', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rohan Laxmanalal', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Maria Kovacic', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Heather Freeman', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Liza Tazewell', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Julian Fayad', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Phil Bradley', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Andrew Charlton', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Steve Christou', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Neil Turner', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Brooke Vitnell', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Meryl Swanson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Angela Ketas', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Louise Ihlein', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sonia Bailey', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jason Mark Olbourne', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sally Sitou', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sahar Khalili-Naghadeh', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Edward Walters', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Natalie Baini', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Andrew Cameron', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Fiona Martin', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jamal Daoud', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Charles Jago', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Terry Patrick Sharples', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Nathan Jones', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Monica Shepherd', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('David Warth', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Gary Biggs', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Justine Elliot', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kimberly Hone', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tracey Bell-Henselin', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Mandy Nolan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Robert James Marks', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Richard Orchard', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Mark Jeffreson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Daniel Martelozzo', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Steve Karaitiana', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Michael Mccormack', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Darren Ciavarella', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Dean Mccrae', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Michael Organ', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Patrick Murphy', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Gordon Reid', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Paul Borthwick', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Lucy Wicks', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Barbara-Jane Murray', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Bentley Logan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jeffrey Wayne Lawson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Billy O`Grady', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kate Mason', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Alexandra Hafner', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Shelly Mcgrath', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Bree Suzanne Roberts', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Basil Paynter', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Barry Reed', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Nell Mcgill', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Pat Conroy', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kenneth John Maxwell', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kim Grierson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Quintin King', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Andrew Chuter', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tanya Plibersek', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ben Ferguson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Chetan Sahai', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Wen Zhou', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ryan Mcalister', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Alexander Andruska', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Steven Tripp', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Zali Steggall', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Andrew Colin Robertson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kristyn Glanville', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Katherine Deves', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('David Mickleburgh', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kate Paterson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sazeda Akter', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('John Koukoulis', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tony Burke', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Alan Jorgensen', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Bradley Schott', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tim Murray', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Dean Fisher', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Dominic Wy Kanak', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Natalie Dumer', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Allegra Spender', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Daniel Lewkovitz', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Dave Sharma', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Victor Tey', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tony Mark Nikolic', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Anne Maree Stanley', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Apurva Shukla', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sam Kayal', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Adam Paul Booke', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Stephen Jones', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Michael Wheeler', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Colin Hughes', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Mike Cains', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Allan Wode', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jamie Dixon', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Damien Ryan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Blair Mcfarland', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Thong Sum Lee', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Allan Mcleod', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Marion Scrymgour', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Michael Setford Gravener', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Imelda Adamson Agars', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tim Gallard', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('George Kasparek', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kylie Bonanni', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Aiya Goodrich Carttling', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Luke Gosling', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tina Macfarlane', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Emily Lohse', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tayla Elise Selfe', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Danielle Mutton', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Michelle Jaques', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Quinton Stewart Cunningham', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Liz Suduk', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Shayne Neumann', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Maria Pitman', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Angela Lowery', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sam Biggins', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ross Vasta', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Amanda Neil', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Serge Diklich', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tabatha Young', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Bernard Lakey', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Walter Todd', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Mary-Jane Stevens', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ian Mazlin', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Henry Pike', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Phil Johnson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Donisha Duff', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tiana Kennedy', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Justin Marc Knudson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Stephen Bates', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Madonna Jarrett', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Trevor Evans', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Trevor Hold', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Anthony Bull', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kylee Stanton', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Paula Ganfield', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Mick Jones', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Russell Robertson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Steve Murphy', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ken Murray', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Nathan Luke Harding', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Michelle Landry', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Zteven Whitty', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Andrew Willcox', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Julie Hall', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Shane Hamilton', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jim Jackson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Christian Nigel Young', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ciaron Paterson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Paula Creen', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Alan Buchbach', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Lloyd Russell', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Peter Dutton', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Thor Prohaska', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tamera Gibson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Alina Karen Ward', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ali France', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Vinnie Batten', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Stewart Gordon Brooker', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Letitia Del Fabbro', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Nathan Grant O`Brien', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sandy Roach', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Stuart Robert', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sally Spain', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Alex Forbes', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ted O`Brien', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Wendy Hazelton', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tash Poole', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Barry Smith', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sue Etheridge', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sinim Barbara Australie', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Lisa Khoury', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sue Ferguson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Craig White', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Nikki Civitarese', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sam Schriever', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Judene Andrews', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Andrew Wallace', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Vickie Breckenridge', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Renay Wells', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tony Richard Moore', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Matt Burnett', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Paul Bambrick', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Carla Svendsen', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sharon Lohse', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Duncan Scott', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tanya Maree Wieden', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Colin Boyce', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Roxanne O`Halloran', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Bert Van Manen', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jordan Hall', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Samuel Holland', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rowan Holzberger', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Seschelle Matterson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tobby Sutherland', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Christopher Greaves', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Linda Mccarthy', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Shari Ware', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Max Chandler-Mather', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Terri Butler', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Robert Gordon Mcmullan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Olivia Roberts', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ryan Otto', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Grant Abraham', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Mickey Berry', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Melissa Bannister', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kirstie Smolenski', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Suzie Holt', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Garth Hamilton', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Gen Allpass', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Toni Mcmahon', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('John Ring', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Scott Humphreys', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Larna Ballard', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Phillip Thompson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Angela Egan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Steven Clare', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Greg Ian Dowling', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Clynton Hawks', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Toni Mccormack', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Diane Pepe', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Keith Pitt', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kristie Nash', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Zak Menhennett', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jason Scanes', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Andrew Mclean', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jack Dempsey', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Bob Katter', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Bryce Macdonald', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jen Sackley', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jennifer Cox', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jason Brandon', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Peter Campion', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Pat O`Shane', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Silvia Mogorovich', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Warren Entsch', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rod Jensen', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Adam Cropp', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Susanne Bayly', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Phillip Musumeci', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Daniel Lucas Hannagan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Geena Court', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Paul Roe', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Elida Faith', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Gerardine Louise Hoogland', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Melissa Stevens', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Vivian Lobo', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Stephen Mcgrath', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Daniel Freshwater', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Anika Wells', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Michelle Wilde', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rebecca Fanning', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Stefanie Alexis Sutherland', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Nigel David Quinlan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Earl Snijders', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ross Taylor', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jens Lipponer', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Paula Gilbard', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Terry Young', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('David Littleproud', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Malcolm J Richardson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Dave Kerrigan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Nathan John Mcdonald', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ellisa Parker', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Mike Kelly', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Brett James Tunbridge', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Karen Andrews', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kevin Hargraves', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Gary Pead', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Scott Turner', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Andy Cullen', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Joshua Lawrence Berrigan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Glenn Pyne', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Carl Ungerer', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Angie Bell', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Leeanne Schultz', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('James Tayler', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sonia Michelle Berry-Law', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('April Broadbent', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Glen Palmer', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Diane Demetre', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Timothy Cudmore', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Diane Olga Happ', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Peter Power', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Neil Swann', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Graham Perrett', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Claire Garton', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Steven Huang', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Chelsea Follett', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Timothy Coombes', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Asha Worsteling', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kyle Mcmillen', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Dylan Kozlowski', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Milton Dick', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kelly Anne Guenoun', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Will Simon', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Anneke Wilson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Marcus Mitchell', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Mick Denton', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Luke Howarth', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Chris Cicchitti', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Paul Darwen', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Neil Cotter', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jeff Crank', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Glen Cookson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Suzanne Clarke', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jim Chalmers', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kathryn Pollard', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Damian Coory', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Janine Rees', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Joel Love', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jina Lipman', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Elizabeth Watson-Brown', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Peter Cossar', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Julian Simmonds', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Axel Dancoisne', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kelli Jacobi', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Nathan Buckley', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tracy Bennett', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Craig Armstrong', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Llew O`Brien', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('John Woodward', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tim Jerome', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Geoff Williams', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Daniel Williams', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Andrea Newland', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Scott Buchholz', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Cassandra Deanne Duffill', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Keith Hicks', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Shonna-Lee Banasiak', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Pam Mccreadie', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Nicole Thompson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Amy Grantham', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Steve Georganas', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sean Allwood', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Matthew Mcmillan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rebecca Galdies', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Faith Gerhard', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Gayle Allwood', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jonathan Pietzsch', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Carlos Quaremba', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Vince Pannell', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Maddy Fry', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rosa Hillam', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tony Pasin', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('David Swiggs', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Mark Braes', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kym Hanton', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jeremy Carter', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Graeme Clark', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Peter Harris', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Aleksandra Nikolic', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Paul Busuttil', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Frankie Bray', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rachel Swift', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jo Dyer', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Louise Miller-Frost', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Bob Couch', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tim White', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Suzanne Waters', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Peter Miller', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Liz Habermann', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Julie Watson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kerry Ann White', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tracey Dempsey', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Richard Carmody', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rowan Ramsey', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Patrick O`Sullivan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Anna Finizio', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Walter Johnson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Mark Butler', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Dianne Richards', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('George Melissourgos', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jamie Witt', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Matt Pastro', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rob De Jonge', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Robert Godfrey-Brown', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Russell Jackson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Amanda Rishworth', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('John Photakis', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sam Enright', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kathleen Bourne', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Abram Nicholas Lazootin', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tony Zappia', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kimberley Drozdoff', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rajan Vaid', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Alan Howard-Jones', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Emma Mustaca', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Marisa Bell', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Padma Chaplin', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jacob Van Raalte', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rebekha Sharkie', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Greg Elliott', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Allison Bluck', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Samantha Mcgrail', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tonya Scott', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Mark Neugebauer', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Alvin Eric Warren', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Matt Burnell', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('David Deex', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Matilda Bawden', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Shawn Lock', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Linda Champion', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Katie Mccusker', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sonja Baram', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Chris Schmidt', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Alexander Allwood', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Angela Fulco', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Stephen Grant', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kathy Scarborough', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('David Sherlock', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Thomas Mcmahon', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Inty Elham', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('James Stevens', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('George Razay', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Bob Salt', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Cecily Rosol', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Bridget Kathleen Archer', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Alison Baker', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Stephen Humble', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kyle Squibb', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Melanie Davy', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ross Hart', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ludo Mineur', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Darren Briggs', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Gavin Pearce', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Scott Rankin', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Chris Lynch', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Darren Scott Bobbermien', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Craig Anthony Garland', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Keone Patrick Martin', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sophie Lehmann', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Duncan White', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Michelle Cameron', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Simon Davis', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ian Ramsden', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Will Coats', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Janet Shelley', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Andrew Wilkie', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Casey Davies', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sandra Galloway', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Anna Bateman', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Julie Collins', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Duane Pitt', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Steve Hindley', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Lisa Matthews', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Chris Hannan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kristy Maree Johnson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Katrina Love', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jade Darko', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Susie Bower', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rhys Griffiths', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Brian Mitchell', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Anna Megan Gralton', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jason Evans', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Troy Robert Pfitzner', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Emma Jane Goyne', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Liz Johnstone', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rebekah Jane Spelman', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Alan Tudge', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Asher Cookson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ryan Bruce', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Craig Ibbotson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Liam Roche', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Mary Doyle', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('John Barnes', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ben Green', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Alex Graham', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kerryn Sedgman', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Terri Elizabeth Pryse-Smith', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rosalie Taxis', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Julia Mcgrath', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Catherine King', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('James Laurie', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Lisa Chesters', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Darin Schade', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Cate Sinclair', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Matt Bansemer', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ben Mihail', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Elijah Suares', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Christine Skrobo', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Matt Babet', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Hayley Deans', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Julian Hill', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('James Moody', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Matthew Kirwan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Mark Preston', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tim Staker-Gunn', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Natalie Abboud', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Maria Vamvakinou', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Joshua Naim', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jerome Small', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Maria Bengtsson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jenny Game', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Craig Cole', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Andrew Klop', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Aaron Violi', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Bill Brindle', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Paul Murphy', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Chris Field', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Trevor Walter Smith', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Peter Sullivan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Anthony Sebastian Bellve', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Claire Ferres Miles', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Gladys Liu', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Thomas Stanfield', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Anthea Antonie', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Aaron Tyrrell', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rod Whitfield', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ryan Dare', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ethelyn King', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sarah Newman', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Melanie Merle Kempson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Dominique Murphy', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Wayne Tseng', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Carina Garland', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rabin Bangaar', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kath Larkin', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Celeste Liddle', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Adrian Whitehead', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jadon Atkinson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Adam La Rosa', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('William Tristan Turner', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ged Kearney', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Stephen Juhasz', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Alex Marshall', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Libby Coker', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Meg Watkins', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Stephanie Asher', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Paul Barker', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Luke Sorensen', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Daniel William Abou-Zeid', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jean-Marie D`Argent', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sue Bull', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jessica Taylor', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Manish Patel', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Simon Northeast', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Robert Jones', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Naomi Adams', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Max Payne', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Shane Murdock', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Richard Marles', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Matt Gregg', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rob Humphreys', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Qian Liu', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Katherine Dolheguy', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Harrison Carr', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Michael Sukkar', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Judith Thompson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Bianca Joy Gidley', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Samantha Bastin', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Natasha Coughlan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Darren Bergwerf', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Peta Murphy', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Damian Willis', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Elizabeth Johnston', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Liam O`Brien', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sharn Coombes', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Scott Middlebrook', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kathryn Woods', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Adrian Kain Irvine', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Alex Van Der End', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Cyndi Marr', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Chrysten Abraham', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Zoe Mckenzie', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jefferson Earl', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Colin Lane', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sarah Russell', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Surbhi Snowball', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Despi O`Connor', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Pamela Engelander', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('David Wood', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Daniel Mulino', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Anthony Cursio', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Bella Mitchell-Sears', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Keith James Aaron Raymond', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sabine De Pyle', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Catherine Robertson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Suzette Rodoreda', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Monica Clark', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sharynn Moors', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Andrew Charles', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Abraham Isac', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Chloe Glasson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rob Braddock', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tim Watts', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Greg Hansford', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Darren Chester', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Gregory Emil Forster', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Marjorie Thorpe', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jim Mcdonald', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jannette Langley', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Alana Galli-Mcrostie', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ellie Jean Sullivan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Brandon Hoult', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('David Segal', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Zoe Daniel', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Lisa Stark', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Catherine Frances Reynolds', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tim Wilson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Martyn Abbott', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Daniel Connor', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Praise Morris', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Michael Virag', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Belle Gibson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Brendan O`Connor', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Steven J Loncar', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tony Dobran', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Paul Lassig', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('John Fletcher', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Michael Williams', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Michael Edward Lacey', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sam Rae', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jarrod James Bingham', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Max Martucci', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Enamul Haque', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Lynda Wheelock', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Nick Suduk', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Glenn Vessey', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jack Hynes', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Andrew Glenn Cuthbertson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Matthew Ford', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ingram Magnus Spencer', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Alicia Walker', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Katie Allen', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Andrew Johnson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Michelle Ananda-Rajah', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Suzie Menoudakis', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sonya Semmens', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ravi Ragupathy', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Cassandra Fernando', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Gerardine Hansen', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sandy Ambard', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Gregory Saldanha', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Matthew Nunez-Silva', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sujit Mathew', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ranj Perera', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Edward Sok', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Clare O`Neil', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Louisa Willoughby', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Bruce Scott Ridgway', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Roger Tull', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Savitri Bevinakoppa', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Angel Aleksov', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Helen Haines', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Lachlan O`Connell', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Stephen Williams', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Beth Stevens', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Benjamin Gilbert', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Liz Fisher', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Nadia David', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Julian Fidge', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ross Lyman', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Boris Sokiransky', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Mark Dreyfus', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sarah O`Donnell', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Robbie Beaton', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Alex Breskin', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Alix Livingstone', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Scott Anson Mccamish', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kate Thwaites', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Brendan Palmarini', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Allison Zelinka', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Zahra Mustaf', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Maya Tesa', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Liz Chase', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('John Booker', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sahil Tomar', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Monique Ryan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Scott Andrew Hardiman', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Alexandra Thom', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Michele Dale', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Josh Coyne', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Will Anderson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Josh Frydenberg', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Peter Lynch', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rachael Nehmer', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Piers Mitchem', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('David Connolly', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jason Wood', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Hadden Ervin', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Michael Schilling', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Merryn Mott', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Abhimanyu Kumar', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rebecca Skinner', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Michael Abelman', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Helen Jeges', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Aijaz Moinuddin', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Claudio Uribe', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Juanita Coral Paterson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Joanne Ryan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Patrizia Barcatta', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Peter Malliaros', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('James Ingarfill', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jack Boddeke', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ravi Gaddipati', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('John B Myers', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Colleen Harkin', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Josh Burns', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Debera Anne', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rob Mccathie', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ben Schultz', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Steph Hodgins-May', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jane Elizabeth Hickey', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Anne Webster', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sophie Baldwin', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Claudia Haenel', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Chris Lahy', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Carole Hart', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sam Mccoll', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Stuart William King', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Vanessa Atkinson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Mark Michael Hobart', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Daniel Nair Dadich', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Bill Shorten', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jodie Tindal', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Darren Besanko', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Mira D`Silva', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rhonda Pryor', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Alexander Anthony Ansalone', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Cameron Smith', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Neil Barker', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Paul Joseph Mcrae', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Christopher Neil', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Chris Bradbury', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('John Herron', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Richard Welch', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rob Mitchell', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Justin Borg', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Keir Paterson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Adam Bandt', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('James Damches', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Richard Peppard', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Scott Robson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Walter Stragan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Bruce Poon', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Colleen Bolger', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Naomi Oakley', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sanjeev Sabhlok', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Greg Cheesman', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('John Hayes', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Keith Wolahan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Bill Pheasant', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Nathan Scaglione', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Mat Morgan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Russell Broadbent', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Deb Leonard', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Allan Hicken', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('David Matthew Welsh', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jessica O`Donnell', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Meg Edwards', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Christine Ann Mcshane', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tim Laird', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sam Birrell', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rikkie-Lee Tyrrell', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Bill Lodwick', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jeff Davy', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Robert Peterson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ian Christoe', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Andrea Otto', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Steve Brooks', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Eleonor Tabone', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rob Priestly', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Patchouli Paterson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ursula Van Bree', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Eric Koelmeyer', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Andrew Giles', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Yassin Albarri', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Virosh Perera', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Cameron Rowe', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Graham Garner', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Dan Tehan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ronnie Graham', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Hilary Mcallister', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Alex Dyson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Craige Kensen', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Amanda Mead', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Gilbert Wilson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tom Wright', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jill Tindal', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Emma Black', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sam Sergi', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sue Bolton', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Irene Zivkovic', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Peter Khalil', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Leah Horsfall', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sarah Jefford', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Madeleine King', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Malcolm Heffernan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Peter Hudson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('David Pike', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Heather Lonsdale', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jayne Crichton', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Michael O`Loghlen', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Alison Marshall', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Andrew Gleeson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jake Taylor', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Michele Castle', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Travis Carter', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Joshua Mccurry', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Daniel Garlett', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Stephen Phelan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('David Goode', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Warnar Spyker', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Matt Keogh', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Andrew Hastie', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Amanda Hunt', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tammi Siwes', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Anthony Gardyne', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('James Gordon Waldeck', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Brad Bedford', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Judith Congrene', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jodie Moffat', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ashley Elphin Williams', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Andriette Du Plessis', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('David Gardiner', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Anne Aly', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Isabella Tripp', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sylvia Iradukunda', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Michael Calautti', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tyler Walsh', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Micah Van Krieken', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Roland Laverack', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Claire Elizabeth Hand', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Vince Connelly', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Michael Anagno', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ladeisha Louise Verhoeff', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Bill Burn', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Judith Cullity', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Celia Hammond', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Dale Marie Grillo', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kate Chaney', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Yannick Spencer', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Cameron Pidgeon', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Craig Shore', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Melissa Price', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Adrian Mcrae', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Anthony James Fels', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jeremiah Riley', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Brenton Johannsen', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ian Blayney', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Bianca Mcneair', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Andrew Charles Middleton', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Helen Allan', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Paul Markham', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Mailee Dunn', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Christine Terrantroy', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Greg Stephens', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tracy Nyree Aitken', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Bronwen English', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Shane Mezger', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Nola Marino', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ben Tilbury', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sam Wainwright', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Cathy Gavranich', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Josh Wilson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Stella Jinman', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Bill Koul', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Felicity Townsend', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Yan Loh', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Janetia Knapp', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('William Edgar', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jeanene Williams', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Brendan Sturcke', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Will Scott', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Pauline Clark', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ian Monck', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ken Wyatt', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Marijanna Smith', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tania Lawrence', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Steven Mccreanor', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sue Andersson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Peter Gunness', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tom French', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Mark Cooper', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ian Goodenough', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Brian Brightman', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Helen Watkinson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Martin Suter', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Stan Kustrin', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Shaneane Weldon', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Giz Watson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Isaac Middle', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Morris Bessant', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Justin Moseley', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tracy Anne Tirronen', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Brenden Barber', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rick Wilson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Roslyn Stewart', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Donna Nelson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('David Marshall', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tracey Roberts', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Trevor Richard Dalby', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jim Paice', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Aaron Malloy', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Linda Aitken', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Vanessa Montgomery', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Nigel March', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Cameron Bailey', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Dean Powell', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sean Connor', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Dave Vos', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sarah Szmekura-Moor', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Patrick Gorman', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Evan Nickols', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sonya Michelle Eberhart', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Caroline Perks', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('David Dwyer', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Aiden Gyuru', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Paul Hilton', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Matthew Thompson', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Timothy Green', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Zaneta Mascarenhas', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Carl Pallier', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Rod Bradley', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Peter Hallifax', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Kristy Mcsweeney', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Clint Uink', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Dena Gower', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Tshung-Hui Chang', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jay Dean Gillett', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Mark Staer', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Travis Llewellyn Mark', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Sam Lim', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Ben Morton', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Brent Fowler', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Jacqueline Holroyd', '');
INSERT INTO `candidates`(`name`, `description`) VALUES ('Adam Abdul Razak', '');
