INSERT INTO `parties`(`name`, `founded`) VALUES ('United Australia Party', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('Pauline Hanson`s One Nation', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('Independent', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('The Greens', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('Liberal Democrats', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('FUSION: Science, Pirate, Secular, Climate Emergency', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('Democratic Alliance', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('Australian Federation Party', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('The Nationals', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('Citizens Party', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('Sustainable Australia Party - Stop Overdevelopment / Corruption', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('Australian Democrats', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('Informed Medical Options Party', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('Shooters, Fishers and Farmers Party', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('Animal Justice Party', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('TNL', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('Indigenous - Aboriginal Party of Australia', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('Socialist Alliance', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('NT CLP', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('Queensland Greens', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('Australian Values Party', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('Liberal National Party of Queensland', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('The Great Australian Party', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('Katter`s Australian Party (KAP)', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('Legalise Cannabis Australia', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('Australian Progressives', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('National Party', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('Centre Alliance', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('Drew Pavlou Democratic Alliance', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('Jacqui Lambie Network', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('The Local Party', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('Victorian Socialists', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('Derryn Hinch`s Justice Party', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('Reason Australia', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('The Greens (WA)', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('Australian Christians', null);
INSERT INTO `parties`(`name`, `founded`) VALUES ('WESTERN AUSTRALIA PARTY', null);
